---
apiVersion: v1
kind: pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    author: nana
spec:
  containers:
    - name: votingapp
      image: dockersamples/examplevotingapp_vote
       - containerPort: 80
...